version: 2.1
jobs:
  build:
    working_directory: ~/circleci-test
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - setup_remote_docker:
            docker_layer_caching: true
      - run:
          command: |
            /usr/local/bin/python -m unittest discover -s tests/
