version: 2.1
jobs:
  build:
    working_directory: ~/circleci-test
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
            pip install coverage==5.0a5
      - run:
          command: |
            coverage run -m unittest discover -s ./tests
            coverage report --omit=*/tests/*,*/venv/*
            coverage html
      - store_artifacts:
          path: htmlcov
